name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup go 1.13
      uses: actions/setup-go@v1
      with: {go-version: '1.13'}
    - name: Set system path
      run: echo "##[add-path]$(go env GOPATH)/bin"
    - run: GO111MODULE=on go get -u github.com/forensicanalysis/artifactcollector
    - run: sudo artifactcollector
    - run: mkdir testdata
    - run: mv *.forensicstore.zip testdata
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: testdata
        path: testdata
